/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift_6 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] c,
    output reg [1:0] f
  );
  
  
  
  always @* begin
    f = 2'h1;
    c = 8'h01;
    
    case (alufn[0+1-:2])
      2'h0: begin
        f = 2'h0;
        c = a << b[0+3-:4];
      end
      2'h1: begin
        f = 2'h0;
        c = a >> b[0+3-:4];
      end
      2'h3: begin
        f = 2'h0;
        c = $signed(a) >>> b[0+3-:4];
      end
    endcase
  end
endmodule
