/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module add_3 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] c,
    output reg z,
    output reg v,
    output reg n,
    output reg [1:0] f
  );
  
  
  
  reg [7:0] sum;
  
  always @* begin
    c = 16'h0000;
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    f = 2'h1;
    sum = 8'h00;
    
    case (alufn[0+0-:1])
      1'h0: begin
        sum = a + b;
        f = 2'h0;
      end
      1'h1: begin
        sum = a - b;
        f = 2'h0;
      end
      default: begin
        sum = 8'h00;
        f = 2'h0;
      end
    endcase
    c = sum;
    z = (~|sum);
    v = (a[7+0-:1] & b[7+0-:1] & (~sum[7+0-:1])) | ((~a[7+0-:1]) & (~b[7+0-:1]) & sum[7+0-:1]);
    n = sum[7+0-:1];
  end
endmodule
