/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boole_5 (
    input [5:0] alufn,
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] c,
    output reg [1:0] f
  );
  
  
  
  integer n;
  
  integer in;
  
  always @* begin
    f = 2'h1;
    c = 16'h0000;
    for (n = 1'h0; n < 4'h8; n = n + 1) begin
      in = {a[(n)*1+0-:1], b[(n)*1+0-:1]};
      
      case (in)
        2'h0: begin
          f = 2'h0;
          c[(n)*1+0-:1] = alufn[0+0-:1];
        end
        2'h1: begin
          f = 2'h0;
          c[(n)*1+0-:1] = alufn[1+0-:1];
        end
        2'h2: begin
          f = 2'h0;
          c[(n)*1+0-:1] = alufn[2+0-:1];
        end
        2'h3: begin
          f = 2'h0;
          c[(n)*1+0-:1] = alufn[3+0-:1];
        end
      endcase
    end
  end
endmodule
